# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/backend/schema.rs"
custom_type_derives = ["diesel_derive_enum"]

[migrations_directory]
dir = "migrations"

# The database URL to use for migrations and schema generation
# This should be set via environment variable DATABASE_URL
# For example: DATABASE_URL=postgresql://username:password@localhost:5432/rust_cms 